# -*- coding: utf-8 -*-
"""Task07.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/heqiaow/Curso2025-2026-ODKG/blob/master/Assignment4/course_materials/notebooks/Task07.ipynb

**Task 07: Querying RDF(s)**
"""

#!pip install rdflib
import urllib.request
url = 'https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/refs/heads/master/Assignment4/course_materials/python/validation.py'
urllib.request.urlretrieve(url, 'validation.py')
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/master/Assignment4/course_materials"

from validation import Report

"""First let's read the RDF file"""

from rdflib import Graph, Namespace, Literal
from rdflib.namespace import RDF, RDFS
# Do not change the name of the variables
g = Graph()
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)
g.parse(github_storage+"/rdf/data06.ttl", format="TTL")
report = Report()

"""**TASK 7.1a: For all classes, list each classURI. If the class belogs to another class, then list its superclass.**
**Do the exercise in RDFLib returning a list of Tuples: (class, superclass) called "result". If a class does not have a super class, then return None as the superclass**
"""

# TO DO

result = [] #list of tuples
for s,p,o in g.triples((None, RDF.type, RDFS.Class)):
  check = g.value(subject=s, predicate=RDFS.subClassOf, object=None)
  result.append((s, check))

# Visualize the results
for r in result:
  print(r)

## Validation: Do not remove
report.validate_07_1a(result)

"""**TASK 7.1b: Repeat the same exercise in SPARQL, returning the variables ?c (class) and ?sc (superclass)**"""

query =  """
select ?c ?sc
where {
  ?c a rdfs:Class .
  optional {
    ?c rdfs:subClassOf ?sc .
    filter (?c != ?sc)
  }
}
"""

for r in g.query(query):
  print(r.c, r.sc)

## Validation: Do not remove
report.validate_07_1b(query,g)

"""**TASK 7.2a: List all individuals of "Person" with RDFLib (remember the subClasses). Return the individual URIs in a list called "individuals"**

"""

ns = Namespace("http://oeg.fi.upm.es/def/people#")

# 1) Get Person and all subclasses (transitively)
person_class = ns.Person
classes = {person_class}
queue = [person_class]

while queue:
    current = queue.pop()
    for subclass, _, _ in g.triples((None, RDFS.subClassOf, current)):
        if subclass not in classes:
            classes.add(subclass)
            queue.append(subclass)

# 2) Get all individuals of Person and its subclasses
indiv_set = set()
for c in classes:
    for s, _, _ in g.triples((None, RDF.type, c)):
        indiv_set.add(s)

# variable to return
individuals = list(indiv_set)

# visualize results
for i in individuals:
  print(i)

# validation. Do not remove
report.validate_07_02a(individuals)

"""**TASK 7.2b: Repeat the same exercise in SPARQL, returning the individual URIs in a variable ?ind**"""

query = """
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ontology: <http://oeg.fi.upm.es/def/people#>

SELECT ?ind
WHERE {
    ?ind rdf:type ?cls .
    ?cls rdfs:subClassOf* ontology:Person .
}
"""

for r in g.query(query):
  print(r.ind)

## Validation: Do not remove
report.validate_07_02b(g, query)

"""**TASK 7.3:  List the name and type of those who know Rocky (in SPARQL only). Use name and type as variables in the query**"""

query = """
PREFIX person: <http://oeg.fi.upm.es/def/people#>
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?name ?type
WHERE {
    ?ind person:knows person:Rocky .
    ?ind rdfs:label ?name .
    ?ind rdf:type ?type .
}
"""

# Visualize the results

for r in g.query(query):
  print(r.name, r.type)

## Validation: Do not remove
report.validate_07_03(g, query)

"""**Task 7.4: List the name of those entities who have a colleague with a dog, or that have a collegue who has a colleague who has a dog (in SPARQL). Return the results in a variable called name**"""

query = """
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX person: <http://oeg.fi.upm.es/def/people#>

SELECT DISTINCT ?name
  WHERE {
    {
      ?person person:hasColleague ?col1 .
      ?col1 person:ownsPet ?pet .
    }
    UNION
    {
      ?person person:hasColleague ?col1 .
      ?col1 person:hasColleague ?col2 .
      ?col2 person:ownsPet ?pet .
    }

    ?person rdfs:label ?name .
  }


"""

for r in g.query(query):
  print(r.name)

# TO DO
# Visualize the results

## Validation: Do not remove
report.validate_07_04(g,query)
report.save_report("_Task_07")
